### ISSUE TITLE
Backup fails due to generated domaincheckpoint xml misses disks elements

### ISSUE THREAD

**Issue by damiankaczkowski** [abbbi/virtnbdbackup#94] opened 2023-01-05 11:46 UTC
**Version used**
1.9.9

**Describe the bug**
I have a guest which fails to backup with error as shown on logs below. This guest is CentOS 7 (which uses raw disk images). Other Debian 9-10-11 guests on the same hypervisor just backups fine (which uses qcow2 disk images).

**Expected behavior**
Guest should just backup.

**Hypervisor information:**
 - OS: Debian 11
 - HV type: plain libvirt

**Logfiles:**
```
[2023-01-05 12:28:43] INFO common - printVersion [MainThread]: Version: 1.9.9 Arguments: /usr/bin/virtnbdbackup -v --syslog --worker 1 --type stream --raw --compress --scratchdir /tmp/virtnbdbackup.scratch.rootdir.fule9THr8l --domain testguest --output /tmp/virtnbdbackup.data.rootdir.uVOEfz0qML/testguest/2023w01 --level auto
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Backup level: [auto]
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Compression enabled, level [2]
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Backup mode auto, target folder is empty: executing full backup.
[2023-01-05 12:28:43] DEBUG client - _connect [MainThread]: Libvirt URI: [qemu:///session]
[2023-01-05 12:28:43] DEBUG client - _connect [MainThread]: Connect libvirt using open function.
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Libvirt library version: [8000000]
[2023-01-05 12:28:43] DEBUG client - getDomainDisks [MainThread]: Disk config file notation
[2023-01-05 12:28:43] INFO client - getDomainDisks [MainThread]: Skipping attached [cdrom] device: [sdb].
[2023-01-05 12:28:43] DEBUG client - getDomainInfo [MainThread]: No setting [loader] found: 'NoneType' object has no attribute 'text'
[2023-01-05 12:28:43] DEBUG client - getDomainInfo [MainThread]: No setting [nvram] found: 'NoneType' object has no attribute 'text'
[2023-01-05 12:28:43] DEBUG client - getDomainInfo [MainThread]: No setting [kernel] found: 'NoneType' object has no attribute 'text'
[2023-01-05 12:28:43] DEBUG client - getDomainInfo [MainThread]: No setting [initrd] found: 'NoneType' object has no attribute 'text'
[2023-01-05 12:28:43] DEBUG client - getDomainInfo [MainThread]: Domain Info: [{}]
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Domain has [1] disks attached which support changed block tracking.
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Concurrent backup processes: [1]
[2023-01-05 12:28:43] INFO client - redefineCheckpoints [MainThread]: Loading checkpoint list from: [/tmp/virtnbdbackup.data.rootdir.uVOEfz0qML/testguest/2023w01/checkpoints]
[2023-01-05 12:28:43] INFO virtnbdbackup - handleCheckpoints [MainThread]: Checkpoint handling.
[2023-01-05 12:28:43] DEBUG client - removeAllCheckpoints [MainThread]: Cleaning up persistent storage /tmp/virtnbdbackup.data.rootdir.uVOEfz0qML/testguest/2023w01/checkpoints
[2023-01-05 12:28:43] INFO virtnbdbackup - handleCheckpoints [MainThread]: Using checkpoint name: [virtnbdbackup.0].
[2023-01-05 12:28:43] DEBUG virtnbdbackup - handleCheckpoints [MainThread]: Checkpoint info: [{'name': 'virtnbdbackup.0', 'parent': '', 'file': '/tmp/virtnbdbackup.data.rootdir.uVOEfz0qML/testguest/2023w01/testguest.cpt'}].
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Local NDB Endpoint socket: [/var/tmp/virtnbdbackup.1923709]
[2023-01-05 12:28:43] INFO virtnbdbackup - main [MainThread]: Temporary scratch file target directory: [/tmp/virtnbdbackup.scratch.rootdir.fule9THr8l]
[2023-01-05 12:28:43] INFO virtnbdbackup - startBackupJob [MainThread]: Starting backup job.
[2023-01-05 12:28:43] DEBUG client - _createBackupXml [MainThread]: Using scratch file: /tmp/virtnbdbackup.scratch.rootdir.fule9THr8l/backup.FBM1Q.sda
[2023-01-05 12:28:43] DEBUG client - _indentXml [MainThread]:
<domainbackup mode="pull">
  <server transport="unix" socket="/var/tmp/virtnbdbackup.1923709"/>
  <disks>
    <disk name="sda">
      <scratch file="/tmp/virtnbdbackup.scratch.rootdir.fule9THr8l/backup.FBM1Q.sda"/>
    </disk>
  </disks>
</domainbackup>
[2023-01-05 12:28:43] DEBUG client - _indentXml [MainThread]:
<domaincheckpoint>
  <description>Backup checkpoint</description>
  <name>virtnbdbackup.0</name>
  <disks/>
</domaincheckpoint>
[2023-01-05 12:28:43] DEBUG client - fsFreeze [MainThread]: Attempting to freeze filesystems.
[2023-01-05 12:28:43] INFO client - fsFreeze [MainThread]: Freezed [7] filesystems.
[2023-01-05 12:28:43] DEBUG client - startBackup [MainThread]: Starting backup job via libvirt API.
[2023-01-05 12:28:43] DEBUG client - fsThaw [MainThread]: Attempting to thaw filesystems.
[2023-01-05 12:28:43] INFO client - fsThaw [MainThread]: Thawed [7] filesystems.
[2023-01-05 12:28:43] ERROR virtnbdbackup - startBackupJob [MainThread]: Failed to start backup: [XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domaincheckpoint.rng
Extra element disks in interleave
Element domaincheckpoint failed to validate content
]
```
**Workaround:**
None.

**Comment by damiankaczkowski** [comment] 2023-01-05 11:50
This is xml definition of guest disk which fails.
```
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='directsync' io='native' discard='unmap'/>
      <source file='/var/lib/libvirt/images/testguest/data/testguest.osdata.img'/>
      <backingStore/>
      <target dev='sda' bus='sata'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
````

**Comment by damiankaczkowski** [comment] 2023-01-05 12:34
Changing level to "--level auto" fixes the problem. Shouldn't "--level auto" handle this case when used with "--raw"?

**Comment by abbbi** [comment] 2023-01-05 13:31
only copy backup works with raw disks (now checkpoints can be created) it should fallback to copy backup if auto is used and --raw is specified.

**Comment by abbbi** [comment] 2023-01-05 13:35
the problem is that the checkpoint should only be created for the first disk. The created checkpoint XML is wrong.

**Comment by abbbi** [comment] 2023-01-05 13:42
can reproduce..

**Comment by abbbi** [comment] 2023-01-05 16:14
should be fixed in dev branch, can you confirm?

**Closed** 2023-01-07 19:16 UTC
Labels: bug, Needs-testing, fixed-in-dev, workaround-exists
