### ISSUE TITLE
Progress show TB of data during backup of ~61GB disk

### ISSUE THREAD

**Issue by slu-010101** [abbbi/virtnbdbackup#160] opened 2024-03-19 09:29 UTC
**Version used**
virtnbdbackup --version
2.0

**Describe the bug**
Progress show TB of data during backup of ~61GB disk, this problem is reproducible.

**Hypervisor information:**
Debian 12.5
libvirt-daemon 9.0.0-4
[virtnbdbackup.log](https://github.com/abbbi/virtnbdbackup/files/14648431/virtnbdbackup.log)
![Screenshot 2024-03-19_10-17](https://github.com/abbbi/virtnbdbackup/assets/11032756/ebf6c242-f9a8-4766-b8af-44fd786062cb)

**Comment by abbbi** [comment] 2024-03-19 09:38
hm.. seems that TQDM (https://github.com/tqdm/tqdm) measuring is off here.

The Logfile reports ~60GB data size to backup:

`root disk - backup [sda]:  64424509440 bytes of data extents to backup`

but the progress bar scales up to TB..
Progressbar is setup with Bytes as unit but with unit_scale option:

https://github.com/abbbi/virtnbdbackup/blob/master/libvirtnbdbackup/common.py#L226

Maybe the parameter for unit_scale=True is wrong and needs an actual size:

```
unit_scale: bool or int or float, optional
If 1 or True, the number of iterations will be reduced/scaled automatically and a metric prefix following the International System of Units standard will be added (kilo, mega, etc.) [default: False]. If any other non-zero number, will scale total and n.
```

the Performance with 357 GB/s is  pretty tight too.
Maybe the Backup finishes so fast TQDM is unable to calcuclate / measure correctly.

**Comment by abbbi** [comment] 2024-03-19 10:11
while i cannot reproduce your situation, the actual progressbar throughput and progress was off since change for issue #133, this has been fixed with following commit:

https://github.com/abbbi/virtnbdbackup/commit/3451ed1a91b4f4ea3e643d7662540a765680bdac

im not sure if it actually solves this problem, but may be related.+

**Comment by slu-010101** [comment] 2024-03-19 12:28
Here the screenshot with 2.1.
![2 1_2024-03-19_13-26](https://github.com/abbbi/virtnbdbackup/assets/11032756/66ac0705-47ab-48b1-a9c7-74b121fc6593)

**Comment by slu-010101** [comment] 2024-03-19 12:33
...and the progress bar is now complete different.
In 2.0 it finished after seconds and in 2.1 its slower and equals to the disk size and ~900MB/s write performance.

**Closed** 2024-03-19 16:10 UTC
Labels: bug, fixed-in-master
