### ISSUE TITLE
LZ4F_decompress failed with code ERROR_blockChecksum_invalid

### ISSUE THREAD

**Issue by sbrunsch2024** [abbbi/virtnbdbackup#134] opened 2023-09-04 18:15 UTC
**Version used**
Provide output of `virtnbdbackup -V`

1.9.38

**Describe the bug**
restore Error

**Expected behavior**
successful restore

**Hypervisor information:**
 - OS: [e.g. Alma, Debian]
 - HV type [e.g. opennebula, plain libvirt, rhev]
libvirt kvm@ debian
 
virtnbdrestore -i /vmbackup/routervm/202309 -o /kvm/storage -N routervm

ERROR root virtnbdrestore - restoreData [MainThread]: LZ4F_decompress failed with code: ERROR_blockChecksum_invalid
Traceback (most recent call last):
  File "/usr/bin/virtnbdrestore", line 142, in restoreData
    written = chunk.read(
              ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/libvirtnbdbackup/chunk.py", line 83, in read
    data = lz4.decompressFrame(reader.read(blocklen))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/libvirtnbdbackup/lz4.py", line 27, in decompressFrame
    return lz4.frame.decompress(data)

No workaround

**Comment by abbbi** [comment] 2023-09-04 18:34
Hi, This Looks Like a corrupt Block in the data file. If compression was enabled during backup the lz4 layer also stores an checksum alongside the compressed block and it appears this checksum doesnt Match anymore. Any notable issues on the filesystem the data is stored on? Is it reproducible with other backups?

**Comment by sbrunsch2024** [comment] 2023-09-04 18:40
I had 2 vms which had this error. I made a fresh backup of both and got the same error with one remaining vm (the biggest one).
Just trying a new backup without compression. But 300GB data take some time for backup and restore.

Target is a NFS-Server with TrueNAS Scale. Message-file from Server and NAS seem to be clean.

**Comment by abbbi** [comment] 2023-09-04 18:50
Is it reproducible it you Backup/ restore to local storage on the hypervisor host? Granted i dont use compression mutch.. at least not with vm this big. The checksum is calculated by the lz4 Module automatically. 

One reason could be that the complete frame read during restore is wrong But that would end in a different error..

**Comment by abbbi** [comment] 2023-09-04 19:12
i just attempted to reproduce this with a backup i did. After backup i replaced one byte within the backup file and attempted restore:

`ERROR root virtnbdrestore - restoreData [MainThread]: LZ4F_decompress failed with code: ERROR_blockChecksum_invalid`

but there seems to be no way to ignore the checksum check (which is obviously OK)

**Comment by sbrunsch2024** [comment] 2023-09-04 19:17
I made a backup to different NFS-Server and I could restore it.
Just doing the restore, but I have to backup my nextcloud data to be safe that I have a working backup. So Backup / Restore jobs now working simultanously.

Two different servers had the same problem...

Network errors? FS-errors?
I will schedule a zfs scrub.

**Comment by abbbi** [comment] 2023-09-05 07:06
ive commited a new feature into the "dev" branch: if backup to regular directory is attempted it now computes an adler32 checksum for the complete data file contents and reports them via logfile:

`[2023-09-05 09:04:24] INFO output target - checksum [vda]: Checksum for file: [/tmp/testme9/vda.inc.virtnbdbackup.1.data.partial]:[3400103635]`

then there is a verify option that allows for verifying that checksum:

```
[2023-09-05 09:05:59] INFO lib common - printVersion [MainThread]: Version: 1.9.39 Arguments: ./virtnbdrestore -i /tmp/testme9/ -o verify
[2023-09-05 09:05:59] INFO root virtnbdrestore - verify [MainThread]: Computing checksum for: /tmp/testme9/vda.full.data
[2023-09-05 09:06:00] INFO root virtnbdrestore - verify [MainThread]: Checksum: 3708554484
[2023-09-05 09:06:00] INFO root virtnbdrestore - verify [MainThread]: Computing checksum for: /tmp/testme9/vda.inc.virtnbdbackup.1.data
[2023-09-05 09:06:00] INFO root virtnbdrestore - verify [MainThread]: Checksum: 3400103635

```

so altered files can be identified more easily no matter if compression is used or not.

**Comment by sbrunsch2024** [comment] 2023-09-05 10:35
In this case it seems to be a problem with the storage. Truenas found some failures in zpool.
But checksum would be very nice, so restore test has not tb done so often...

**Comment by abbbi** [comment] 2023-09-05 10:57
thanks for the update! Closing this one ..

**Closed by abbbi** 2023-09-05 10:57 UTC
Labels: Needs-testing, support

**Comment by abbbi** [comment] 2023-09-06 04:40
@sbrunsch2024 latest master now contains this feature, see:

https://github.com/abbbi/virtnbdbackup#verifying-created-backups

of course only works with new backups. Could you test? Thanks.

**Comment by sbrunsch2024** [comment] 2023-09-06 05:02
I already cloned master.

I have to restore my main vm now. I will try it later this day.

**Comment by sbrunsch2024** [comment] 2023-09-06 05:07
￼

Backup is running. Checksums are saved.
——————————————————————————
Stephan Brunsch
Töpchiner Weg 180
12309 Berlin

**Comment by sbrunsch2024** [comment] 2023-09-06 05:12
Any chance to implement checksum verify in backup process?

**Comment by sbrunsch2024** [comment] 2023-09-06 05:27
Last questions before waiting for reaction….

How to modify a bit of a backup file? dd ?

Is there a way to speed up checksum creation?

It takes about 3 minutes for 30 GB on rotating disks.

**Comment by abbbi** [comment] 2023-09-06 06:38
> Last questions before waiting for reaction…. How to modify a bit of a backup file? dd ? 

hexeditor or dd

> Is there a way to speed up checksum creation? It takes about 3 minutes for 30 GB on rotating disks.

you mean verify? Its using 4k blocks to compute the checksum during verify, that might be a bottleneck.
I just added option -B to be able to specify a bigger buffer size.
Default is now io.DEFAULT_BUFFER_SIZE (8k) but might be changed accordingly to suite the environment:

```
 virtnbdrestore -i /tmp/BACKUP -o verify -B 8096 -v
 DEBUG root virtnbdrestore - verify [MainThread]: Using buffer size: 8192
 [..]
 virtnbdrestore -i /tmp/BACKUP -o verify -B 16384 -v
DEBUG root virtnbdrestore - verify [MainThread]: Using buffer size: 16384
```

**Comment by abbbi** [comment] 2023-09-06 06:44
or simply append something to the backup file:

```
# echo 1 >> /tmp/BACKUP/vda.copy.data
# ./virtnbdrestore -i /tmp/BACKUP -o verify -B 16384 -v
[2023-09-06 08:43:16] INFO lib common - printVersion [MainThread]: Version: 1.9.41 Arguments: ./virtnbdrestore -i /tmp/BACKUP -o verify -B 16384 -v
[2023-09-06 08:43:16] DEBUG lib common - getLatest [MainThread]: Sorted data files: 
['/tmp/BACKUP/vda.copy.data']
[2023-09-06 08:43:16] DEBUG root virtnbdrestore - verify [MainThread]: Using buffer size: 16384
[2023-09-06 08:43:16] INFO root virtnbdrestore - verify [MainThread]: Computing checksum for: /tmp/BACKUP/vda.copy.data
[2023-09-06 08:43:17] INFO root virtnbdrestore - verify [MainThread]: Checksum result: 4208209834
[2023-09-06 08:43:17] INFO root virtnbdrestore - verify [MainThread]: Comparing checksum with stored information
[2023-09-06 08:43:17] ERROR root virtnbdrestore - verify [MainThread]: Stored sums do not match: [2609524591]!=[4208209834]
```
